
name: $(date:yyyyMMdd)$(rev:.r)
stages:
  - stage: Build
    jobs:
      - job: Job_1
        displayName: Build and Deploy Image
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
          - task: Npm@1
            displayName: npm install
            inputs:
              command: 'ci'
              workingDir: '$(System.DefaultWorkingDirectory)'
          - task: Docker@2
            displayName: 'Build image'
            inputs:
              containerRegistry: 'WWF Container Registry'
              repository: 'workwithfamilyUI'
              command: 'buildAndPush'
              Dockerfile: './Dockerfile'
              tags: |
                $(Build.BuildNumber)
                Latest