version: 2.1
orbs:
  azure-acr: circleci/azure-acr@0.2.1
workflows:
  build-and-publish-docker-image:
    jobs:
      - azure-acr/build-and-push-image:
          login-server-name: workwithfamily.azurecr.io
          registry-name: workwithfamily
          repo: workwithfamilyui
          tag: latest